# Generated by Django 5.0.1 on 2024-01-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео'),
        ),
    ]
